CREATE TABLE IF NOT EXISTS order_status_undo_events (
  id VARCHAR(64) NOT NULL,
  order_id VARCHAR(64) NOT NULL,
  order_number VARCHAR(100) NOT NULL,
  from_status VARCHAR(32) NOT NULL,
  to_status VARCHAR(32) NOT NULL,
  source_action VARCHAR(64) NOT NULL,
  before_snapshot LONGTEXT NOT NULL,
  after_snapshot LONGTEXT NOT NULL,
  transaction_ids LONGTEXT NULL,
  wallet_entry_ids LONGTEXT NULL,
  stock_deltas LONGTEXT NULL,
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  undone_at DATETIME NULL,
  undone_by VARCHAR(64) NULL,
  undo_batch_id VARCHAR(64) NULL,
  PRIMARY KEY (id),
  KEY idx_order_status_undo_events_order_active (order_id, undone_at, created_at),
  KEY idx_order_status_undo_events_batch (undo_batch_id),
  CONSTRAINT fk_order_status_undo_events_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
  CONSTRAINT fk_order_status_undo_events_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_order_status_undo_events_undone_by FOREIGN KEY (undone_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
