-- SMS Service and automatic SMS settings.
CREATE TABLE IF NOT EXISTS sms_settings (
  id VARCHAR(64) NOT NULL,
  api_key TEXT NULL,
  auto_enabled TINYINT(1) NOT NULL DEFAULT 0,
  send_timing VARCHAR(32) NOT NULL DEFAULT 'after_order',
  call_statuses TEXT NULL,
  templates LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sms_history (
  id VARCHAR(64) NOT NULL, customer_ids LONGTEXT NULL, recipients TEXT NULL,
  message TEXT NOT NULL, status VARCHAR(32) NOT NULL, response LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sms_recharges (
  id VARCHAR(64) NOT NULL, local_reference VARCHAR(64) NULL, gateway_payment_id VARCHAR(255) NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0.00, status VARCHAR(32) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;