import React from 'react';

const PrivacyPolicy: React.FC = () => {
  return (
    <main className="min-h-screen bg-[#f5f7fb] px-4 py-10 text-slate-800 sm:px-6 sm:py-16">
      <article className="mx-auto max-w-4xl overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <header className="border-b border-slate-200 bg-[#0f2f57] px-6 py-8 text-white sm:px-10 sm:py-10">
          <p className="text-sm font-semibold uppercase tracking-[0.18em] text-blue-100">Mame Studios</p>
          <h1 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Privacy Policy for Mame Pilot</h1>
          <p className="mt-4 text-sm text-blue-100">Last Updated: 13th September 2026</p>
        </header>

        <div className="space-y-8 px-6 py-8 sm:px-10 sm:py-10">
          <section>
            <h2 className="text-xl font-bold text-slate-950">1. Introduction</h2>
            <p className="mt-3 leading-7 text-slate-600">
              Mame Studios operates Mame Pilot. This Privacy Policy explains how we collect, use, and process user data, including data obtained from Meta Platforms Technologies, when you connect your Facebook Page to our services.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-950">2. Data We Collect</h2>
            <p className="mt-3 leading-7 text-slate-600">
              When you authorize Mame Pilot to integrate with your Facebook Page, we collect and process specific User Data to provide our core features. This includes:
            </p>
            <ul className="mt-4 list-disc space-y-3 pl-5 leading-7 text-slate-600 marker:text-[#0f2f57]">
              <li><strong className="font-bold text-slate-800">Page Metadata:</strong> Page IDs, names, and permanent access tokens required to maintain a connection to your Meta App.</li>
              <li><strong className="font-bold text-slate-800">Messenger Data:</strong> The content of incoming customer messages sent to your Facebook Page, sender profile information, and the replies generated by authorized administrators.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-950">3. How We Process and Use Data</h2>
            <p className="mt-3 leading-7 text-slate-600">
              We process the collected User Data exclusively for the purpose of operating Mame Pilot. Specifically, this data is used to:
            </p>
            <ul className="mt-4 list-disc space-y-3 pl-5 leading-7 text-slate-600 marker:text-[#0f2f57]">
              <li>Populate the unified customer support inbox within your dashboard.</li>
              <li>Allow authorized Page Administrators to read, manage, and reply to customer inquiries directly from our interface.</li>
              <li>Ensure the application functions properly and securely.</li>
            </ul>
            <p className="mt-4 leading-7 text-slate-600">We do not use Meta Platform Data for advertising, profiling, or unauthorized tracking.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-950">4. Data Sharing and Third Parties</h2>
            <p className="mt-3 leading-7 text-slate-600">
              We do not sell your Meta User Data. Data is only shared with trusted cloud hosting providers that securely store the information necessary to operate the platform. These providers are bound by strict confidentiality agreements.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-950">5. Data Retention and Deletion</h2>
            <p className="mt-3 leading-7 text-slate-600">We retain User Data only as long as your Facebook Page remains connected to our platform. Users can request the complete deletion of their data at any time.</p>
            <ul className="mt-4 list-disc space-y-3 pl-5 leading-7 text-slate-600 marker:text-[#0f2f57]">
              <li><strong className="font-bold text-slate-800">Automated Disconnection:</strong> You can remove access via your Facebook Business Integrations settings.</li>
              <li><strong className="font-bold text-slate-800">Manual Deletion Request:</strong> To permanently delete all stored messaging and account data from our servers, please contact us at [Insert Support Email]. We will process and complete data deletion requests within 7 days.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-950">6. Contact Us</h2>
            <p className="mt-3 leading-7 text-slate-600">
              For questions regarding this policy, please contact Mame Studios at{' '}
              <a className="font-semibold text-[#0f2f57] underline underline-offset-4" href="mailto:mamestudiosbd@gmail.com">mamestudiosbd@gmail.com</a>.
            </p>
          </section>
        </div>

        <footer className="border-t border-slate-200 px-6 py-6 sm:px-10">
          <a className="text-sm font-semibold text-[#0f2f57] hover:underline" href="/#/login">Return to Mame Pilot</a>
        </footer>
      </article>
    </main>
  );
};

export default PrivacyPolicy;
