param(
  [string]$SchemaFile = 'backend/database/schema.sql',
  [string]$SeedFile = 'backend/database/seed.sql',
  [string]$OutputFile = 'backend/database/schema-only.sql'
)

$ErrorActionPreference = 'Stop'
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$schemaPath = Join-Path $repoRoot $SchemaFile
$seedPath = Join-Path $repoRoot $SeedFile
$outputPath = Join-Path $repoRoot $OutputFile

if (-not (Test-Path $schemaPath)) { throw "Schema file not found: $schemaPath" }
if (-not (Test-Path $seedPath)) { throw "Seed file not found: $seedPath" }

$schema = Get-Content -Raw $schemaPath
$seed = Get-Content -Raw $seedPath
$header = "-- Legacy combined fresh-install file.`r`n-- Generated from schema.sql + seed.sql. Do not edit this file directly.`r`n`r`n"
Set-Content -Path $outputPath -Value ($header + $schema.TrimEnd() + "`r`n`r`n" + $seed.TrimEnd() + "`r`n") -Encoding utf8
Write-Host "Synced $OutputFile"
